INSERT INTO AUTHORITY(AUTHORITY_NAME, AUTHORITY_DESC, CREATE_DT)
VALUES('ANNONYMOUS', '익명권한', CURRENT_TIMESTAMP()); -- 1
INSERT INTO AUTHORITY(AUTHORITY_NAME, AUTHORITY_DESC, CREATE_DT)
VALUES('ASSOCIATE_MEMBER_BOARD_READ', '준회원 게시판 읽기', CURRENT_TIMESTAMP()); -- 2
INSERT INTO AUTHORITY(AUTHORITY_NAME, AUTHORITY_DESC, CREATE_DT)
VALUES('ASSOCIATE_MEMBER_BOARD_WRITE', '준회원 게시판 쓰기', CURRENT_TIMESTAMP()); -- 3
INSERT INTO AUTHORITY(AUTHORITY_NAME, AUTHORITY_DESC, CREATE_DT)
VALUES('REGULAR_MEMBER_BOARD_READ', '정회원 게시판 읽기', CURRENT_TIMESTAMP()); -- 4
INSERT INTO AUTHORITY(AUTHORITY_NAME, AUTHORITY_DESC, CREATE_DT)
VALUES('REGULAR_MEMBER_BOARD_WRITE', '정회원 게시판 쓰기', CURRENT_TIMESTAMP()); -- 5
INSERT INTO AUTHORITY(AUTHORITY_NAME, AUTHORITY_DESC, CREATE_DT)
VALUES('NOTICE_READ', '공지 게시판 읽기', CURRENT_TIMESTAMP()); -- 6
INSERT INTO AUTHORITY(AUTHORITY_NAME, AUTHORITY_DESC, CREATE_DT)
VALUES('NOTICE_WRITE', '공지 게시판 쓰기', CURRENT_TIMESTAMP()); -- 7
INSERT INTO AUTHORITY(AUTHORITY_NAME, AUTHORITY_DESC, CREATE_DT)
VALUES('PDS_READ', '자료실 읽기', CURRENT_TIMESTAMP()); -- 8
INSERT INTO AUTHORITY(AUTHORITY_NAME, AUTHORITY_DESC, CREATE_DT)
VALUES('PDS_WRITE', '자료실 쓰기', CURRENT_TIMESTAMP()); -- 9

/*
INSERT INTO URL_RESOURCES(RESOURCE_NAME, RESOURCE_PATTERN, REQUEST_MATCHER_TYPE, ORDERNUM, CREATE_DT) -- 1
VALUES('준회원 게시판 목록', '\/board\/list\.html((\?type=associate(\&[a-zA-Z0-9_]+\=[a-zA-Z0-9_]+)*)|(\?[a-zA-Z0-9_]+\=[a-zA-Z0-9_]+(\&[a-zA-Z0-9_]+\=[a-zA-Z0-9_]+)*\&type=regular(\&[a-zA-Z0-9_]+\=[a-zA-Z0-9_]+)*))', 'REGEX', 1, CURRENT_TIMESTAMP());
INSERT INTO URL_RESOURCES(RESOURCE_NAME, RESOURCE_PATTERN, REQUEST_MATCHER_TYPE, ORDERNUM, CREATE_DT) -- 2
VALUES('준회원 게시판 상세화면', '\/board\/view\.html((\?type=associate(\&[a-zA-Z0-9_]+\=[a-zA-Z0-9_]+)*)|(\?[a-zA-Z0-9_]+\=[a-zA-Z0-9_]+(\&[a-zA-Z0-9_]+\=[a-zA-Z0-9_]+)*\&type=regular(\&[a-zA-Z0-9_]+\=[a-zA-Z0-9_]+)*))', 'REGEX', 1, CURRENT_TIMESTAMP());
INSERT INTO URL_RESOURCES(RESOURCE_NAME, RESOURCE_PATTERN, REQUEST_MATCHER_TYPE, ORDERNUM, CREATE_DT) -- 3
VALUES('준회원 게시판 등록', '\/board\/write\.html((\?type=associate(\&[a-zA-Z0-9_]+\=[a-zA-Z0-9_]+)*)|(\?[a-zA-Z0-9_]+\=[a-zA-Z0-9_]+(\&[a-zA-Z0-9_]+\=[a-zA-Z0-9_]+)*\&type=regular(\&[a-zA-Z0-9_]+\=[a-zA-Z0-9_]+)*))', 'REGEX', 1, CURRENT_TIMESTAMP());
INSERT INTO URL_RESOURCES(RESOURCE_NAME, RESOURCE_PATTERN, REQUEST_MATCHER_TYPE, ORDERNUM, CREATE_DT) -- 4
VALUES('준회원 게시판 수정', '\/board\/update\.html((\?type=associate(\&[a-zA-Z0-9_]+\=[a-zA-Z0-9_]+)*)|(\?[a-zA-Z0-9_]+\=[a-zA-Z0-9_]+(\&[a-zA-Z0-9_]+\=[a-zA-Z0-9_]+)*\&type=regular(\&[a-zA-Z0-9_]+\=[a-zA-Z0-9_]+)*))', 'REGEX', 1, CURRENT_TIMESTAMP());
INSERT INTO URL_RESOURCES(RESOURCE_NAME, RESOURCE_PATTERN, REQUEST_MATCHER_TYPE, ORDERNUM, CREATE_DT) -- 5
VALUES('정회원 게시판 목록', '\/board\/list\.html((\?type=regular(\&[a-zA-Z0-9_]+\=[a-zA-Z0-9_]+)*)|(\?[a-zA-Z0-9_]+\=[a-zA-Z0-9_]+(\&[a-zA-Z0-9_]+\=[a-zA-Z0-9_]+)*\&type=regular(\&[a-zA-Z0-9_]+\=[a-zA-Z0-9_]+)*))', 'REGEX', 1, CURRENT_TIMESTAMP());
INSERT INTO URL_RESOURCES(RESOURCE_NAME, RESOURCE_PATTERN, REQUEST_MATCHER_TYPE, ORDERNUM, CREATE_DT) -- 6
VALUES('정회원 게시판 상세화면', '\/board\/view\.html((\?type=regular(\&[a-zA-Z0-9_]+\=[a-zA-Z0-9_]+)*)|(\?[a-zA-Z0-9_]+\=[a-zA-Z0-9_]+(\&[a-zA-Z0-9_]+\=[a-zA-Z0-9_]+)*\&type=regular(\&[a-zA-Z0-9_]+\=[a-zA-Z0-9_]+)*))', 'REGEX', 1, CURRENT_TIMESTAMP());
INSERT INTO URL_RESOURCES(RESOURCE_NAME, RESOURCE_PATTERN, REQUEST_MATCHER_TYPE, ORDERNUM, CREATE_DT) -- 7
VALUES('정회원 게시판 등록', '\/board\/write\.html((\?type=regular(\&[a-zA-Z0-9_]+\=[a-zA-Z0-9_]+)*)|(\?[a-zA-Z0-9_]+\=[a-zA-Z0-9_]+(\&[a-zA-Z0-9_]+\=[a-zA-Z0-9_]+)*\&type=regular(\&[a-zA-Z0-9_]+\=[a-zA-Z0-9_]+)*))', 'REGEX', 1, CURRENT_TIMESTAMP());
INSERT INTO URL_RESOURCES(RESOURCE_NAME, RESOURCE_PATTERN, REQUEST_MATCHER_TYPE, ORDERNUM, CREATE_DT) -- 8
VALUES('정회원 게시판 수정', '\/board\/update\.html((\?type=regular(\&[a-zA-Z0-9_]+\=[a-zA-Z0-9_]+)*)|(\?[a-zA-Z0-9_]+\=[a-zA-Z0-9_]+(\&[a-zA-Z0-9_]+\=[a-zA-Z0-9_]+)*\&type=regular(\&[a-zA-Z0-9_]+\=[a-zA-Z0-9_]+)*))', 'REGEX', 1, CURRENT_TIMESTAMP());
*/

INSERT INTO URL_RESOURCES(RESOURCE_NAME, RESOURCE_PATTERN, REQUEST_MATCHER_TYPE, ORDERNUM, CREATE_DT) -- 1
VALUES('준회원 게시판 목록', '/associate/board/list.html', 'ANT', 1, CURRENT_TIMESTAMP());
INSERT INTO URL_RESOURCES(RESOURCE_NAME, RESOURCE_PATTERN, REQUEST_MATCHER_TYPE, ORDERNUM, CREATE_DT) -- 2
VALUES('준회원 게시판 상세화면', '/associate/board/view.html', 'ANT', 1, CURRENT_TIMESTAMP());
INSERT INTO URL_RESOURCES(RESOURCE_NAME, RESOURCE_PATTERN, REQUEST_MATCHER_TYPE, ORDERNUM, CREATE_DT) -- 3
VALUES('준회원 게시판 등록', '/associate/board/write.html', 'ANT', 1, CURRENT_TIMESTAMP());
INSERT INTO URL_RESOURCES(RESOURCE_NAME, RESOURCE_PATTERN, REQUEST_MATCHER_TYPE, ORDERNUM, CREATE_DT) -- 4
VALUES('준회원 게시판 수정', '/associate/board/update.html', 'ANT', 1, CURRENT_TIMESTAMP());
INSERT INTO URL_RESOURCES(RESOURCE_NAME, RESOURCE_PATTERN, REQUEST_MATCHER_TYPE, ORDERNUM, CREATE_DT) -- 5
VALUES('정회원 게시판 목록', '/regular/board/list.html', 'ANT', 1, CURRENT_TIMESTAMP());
INSERT INTO URL_RESOURCES(RESOURCE_NAME, RESOURCE_PATTERN, REQUEST_MATCHER_TYPE, ORDERNUM, CREATE_DT) -- 6
VALUES('정회원 게시판 상세화면', '/regular/board/view.html', 'ANT', 1, CURRENT_TIMESTAMP());
INSERT INTO URL_RESOURCES(RESOURCE_NAME, RESOURCE_PATTERN, REQUEST_MATCHER_TYPE, ORDERNUM, CREATE_DT) -- 7
VALUES('정회원 게시판 등록', '/regular/board/write.html', 'ANT', 1, CURRENT_TIMESTAMP());
INSERT INTO URL_RESOURCES(RESOURCE_NAME, RESOURCE_PATTERN, REQUEST_MATCHER_TYPE, ORDERNUM, CREATE_DT) -- 8
VALUES('정회원 게시판 수정', '/regular/board/update.html', 'ANT', 1, CURRENT_TIMESTAMP());

INSERT INTO URL_RESOURCES(RESOURCE_NAME, RESOURCE_PATTERN, REQUEST_MATCHER_TYPE, ORDERNUM, CREATE_DT) -- 9
VALUES('공지 게시판 목록', '/notice/list.html', 'ANT', 1, CURRENT_TIMESTAMP());
INSERT INTO URL_RESOURCES(RESOURCE_NAME, RESOURCE_PATTERN, REQUEST_MATCHER_TYPE, ORDERNUM, CREATE_DT) -- 10
VALUES('공지 게시판 상세화면', '/notice/view.html', 'ANT', 1, CURRENT_TIMESTAMP());
INSERT INTO URL_RESOURCES(RESOURCE_NAME, RESOURCE_PATTERN, REQUEST_MATCHER_TYPE, ORDERNUM, CREATE_DT) -- 11
VALUES('자료실 목록', '/pds/list.html', 'ANT', 1, CURRENT_TIMESTAMP());
INSERT INTO URL_RESOURCES(RESOURCE_NAME, RESOURCE_PATTERN, REQUEST_MATCHER_TYPE, ORDERNUM, CREATE_DT) -- 12
VALUES('자료실 상세화면', '/pds/view.html', 'ANT', 1, CURRENT_TIMESTAMP());




INSERT INTO URL_RESOURCES_AUTHORITY(URL_RESOURCES_IDX, AUTHORITY_IDX)
VALUES(1, 2);
INSERT INTO URL_RESOURCES_AUTHORITY(URL_RESOURCES_IDX, AUTHORITY_IDX)
VALUES(1, 3);
INSERT INTO URL_RESOURCES_AUTHORITY(URL_RESOURCES_IDX, AUTHORITY_IDX)
VALUES(2, 2);
INSERT INTO URL_RESOURCES_AUTHORITY(URL_RESOURCES_IDX, AUTHORITY_IDX)
VALUES(2, 3);
INSERT INTO URL_RESOURCES_AUTHORITY(URL_RESOURCES_IDX, AUTHORITY_IDX)
VALUES(3, 3);
INSERT INTO URL_RESOURCES_AUTHORITY(URL_RESOURCES_IDX, AUTHORITY_IDX)
VALUES(4, 3);
INSERT INTO URL_RESOURCES_AUTHORITY(URL_RESOURCES_IDX, AUTHORITY_IDX)
VALUES(5, 4);
INSERT INTO URL_RESOURCES_AUTHORITY(URL_RESOURCES_IDX, AUTHORITY_IDX)
VALUES(5, 5);
INSERT INTO URL_RESOURCES_AUTHORITY(URL_RESOURCES_IDX, AUTHORITY_IDX)
VALUES(6, 4);
INSERT INTO URL_RESOURCES_AUTHORITY(URL_RESOURCES_IDX, AUTHORITY_IDX)
VALUES(6, 5);
INSERT INTO URL_RESOURCES_AUTHORITY(URL_RESOURCES_IDX, AUTHORITY_IDX)
VALUES(7, 5);
INSERT INTO URL_RESOURCES_AUTHORITY(URL_RESOURCES_IDX, AUTHORITY_IDX)
VALUES(8, 5);
INSERT INTO URL_RESOURCES_AUTHORITY(URL_RESOURCES_IDX, AUTHORITY_IDX)
VALUES(9, 6);
INSERT INTO URL_RESOURCES_AUTHORITY(URL_RESOURCES_IDX, AUTHORITY_IDX)
VALUES(10, 6);
INSERT INTO URL_RESOURCES_AUTHORITY(URL_RESOURCES_IDX, AUTHORITY_IDX)
VALUES(11, 8);
INSERT INTO URL_RESOURCES_AUTHORITY(URL_RESOURCES_IDX, AUTHORITY_IDX)
VALUES(12, 8);

INSERT INTO ROLE(ROLE_NAME, ROLE_DESC, PARENT_ROLE_IDX, CREATE_DT)
VALUES('ADMIN', '관리자', null, CURRENT_TIMESTAMP());             -- 1
INSERT INTO ROLE(ROLE_NAME, ROLE_DESC, PARENT_ROLE_IDX, CREATE_DT)
VALUES('ASSOCIATE_MEMBER', '준회원', null, CURRENT_TIMESTAMP());  -- 2
INSERT INTO ROLE(ROLE_NAME, ROLE_DESC, PARENT_ROLE_IDX, CREATE_DT)
VALUES('REGULAR_MEMBER', '정회원', null, CURRENT_TIMESTAMP());    -- 3
INSERT INTO ROLE(ROLE_NAME, ROLE_DESC, PARENT_ROLE_IDX, CREATE_DT)
VALUES('EXCELLENT_MEMBER', '우수회원', null, CURRENT_TIMESTAMP());   -- 4
INSERT INTO ROLE(ROLE_NAME, ROLE_DESC, PARENT_ROLE_IDX, CREATE_DT)
VALUES('PUNISHMENT_MEMBER', '징계회원', null, CURRENT_TIMESTAMP());   -- 5
UPDATE ROLE SET PARENT_ROLE_IDX = 3 WHERE IDX=2; -- 준회원의 상급 ROLE을 정회원으로 설정하는 UPDATE 문
UPDATE ROLE SET PARENT_ROLE_IDX = 4 WHERE IDX=3; -- 정회원의 상급 ROLE을 우수회원으로 설정하는 UPDATE 문
UPDATE ROLE SET PARENT_ROLE_IDX = 1 WHERE IDX=4; -- 우수회원의 상급 ROLE을 관리자로 설정하는 UPDATE 문
UPDATE ROLE SET PARENT_ROLE_IDX = 3 WHERE IDX=5; -- 징계회원의 상급 ROLE을 정회원으로 설정하는 UPDATE 문(징계회원과 준회원의 회원 등급을 동등한 상태로 설정)


INSERT INTO ROLE_AUTHORITY(ROLE_IDX, AUTHORITY_IDX)
VALUES(2, 2);
INSERT INTO ROLE_AUTHORITY(ROLE_IDX, AUTHORITY_IDX)
VALUES(2, 3);
INSERT INTO ROLE_AUTHORITY(ROLE_IDX, AUTHORITY_IDX)
VALUES(2, 6);
-- INSERT INTO ROLE_AUTHORITY(ROLE_IDX, AUTHORITY_IDX)
-- VALUES(1, 4);
INSERT INTO ROLE_AUTHORITY(ROLE_IDX, AUTHORITY_IDX)
VALUES(3, 4);
INSERT INTO ROLE_AUTHORITY(ROLE_IDX, AUTHORITY_IDX)
VALUES(3, 5);
INSERT INTO ROLE_AUTHORITY(ROLE_IDX, AUTHORITY_IDX)
VALUES(3, 6);


INSERT INTO MEMBER(NAME, LOGIN_ID, LOGIN_PASSWORD, CREATE_DT)
VALUES('준회원이름', 'junmemberid', '$2a$10$gkK3hCHFrKT.LJPlR7Bvj.KxSIYkcIOSqokvsHB80/rlGvKnmwBbq', CURRENT_TIMESTAMP());
INSERT INTO MEMBER(NAME, LOGIN_ID, LOGIN_PASSWORD, CREATE_DT)
VALUES('정회원이름', 'jungmemberid', '$2a$10$gkK3hCHFrKT.LJPlR7Bvj.KxSIYkcIOSqokvsHB80/rlGvKnmwBbq', CURRENT_TIMESTAMP());

INSERT INTO MEMBER_ROLE(MEMBER_IDX, ROLE_IDX)
VALUES(1, 2);
INSERT INTO MEMBER_ROLE(MEMBER_IDX, ROLE_IDX)
VALUES(2, 3);

INSERT INTO MEMBER_AUTHORITY(MEMBER_IDX, AUTHORITY_IDX)
VALUES(2, 6);
INSERT INTO MEMBER_AUTHORITY(MEMBER_IDX, AUTHORITY_IDX)
VALUES(2, 7);



/*
INSERT INTO URL_RESOURCES(RESOURCE_NAME, RESOURCE_PATTERN, REQUEST_MATCHER_TYPE, ORDERNUM, CREATE_DT)
VALUES('회원 게시판 목록', '/board/list.html', 'ANT', 1, CURRENT_TIMESTAMP()); -- 1
INSERT INTO URL_RESOURCES(RESOURCE_NAME, RESOURCE_PATTERN, REQUEST_MATCHER_TYPE, ORDERNUM, CREATE_DT)
VALUES('회원 게시판 상세화면', '/board/view.html', 'ANT', 1, CURRENT_TIMESTAMP()); -- 2
INSERT INTO URL_RESOURCES(RESOURCE_NAME, RESOURCE_PATTERN, REQUEST_MATCHER_TYPE, ORDERNUM, CREATE_DT)
VALUES('회원 게시판 등록', '/board/write.html', 'ANT', 1, CURRENT_TIMESTAMP()); -- 3
INSERT INTO URL_RESOURCES(RESOURCE_NAME, RESOURCE_PATTERN, REQUEST_MATCHER_TYPE, ORDERNUM, CREATE_DT)
VALUES('회원 게시판 수정', '/board/update.html', 'ANT', 1, CURRENT_TIMESTAMP()); -- 4
INSERT INTO URL_RESOURCES(RESOURCE_NAME, RESOURCE_PATTERN, REQUEST_MATCHER_TYPE, ORDERNUM, CREATE_DT)
VALUES('공지 게시판 목록', '/notice/list.html', 'ANT', 1, CURRENT_TIMESTAMP()); -- 5
INSERT INTO URL_RESOURCES(RESOURCE_NAME, RESOURCE_PATTERN, REQUEST_MATCHER_TYPE, ORDERNUM, CREATE_DT)
VALUES('공지 게시판 상세화면', '/notice/view.html', 'ANT', 1, CURRENT_TIMESTAMP()); -- 6
INSERT INTO URL_RESOURCES(RESOURCE_NAME, RESOURCE_PATTERN, REQUEST_MATCHER_TYPE, ORDERNUM, CREATE_DT)
VALUES('자료실 목록', '/pds/list.html', 'ANT', 1, CURRENT_TIMESTAMP()); -- 7
INSERT INTO URL_RESOURCES(RESOURCE_NAME, RESOURCE_PATTERN, REQUEST_MATCHER_TYPE, ORDERNUM, CREATE_DT)
VALUES('자료실 상세화면', '/pds/view.html', 'ANT', 1, CURRENT_TIMESTAMP()); -- 8
*/