INSERT INTO AUTHORITY(AUTHORITY_NAME, AUTHORITY_DESC, CREATE_DT)
VALUES('ANNONYMOUS', '익명권한', CURRENT_TIMESTAMP()); -- 1
INSERT INTO AUTHORITY(AUTHORITY_NAME, AUTHORITY_DESC, CREATE_DT)
VALUES('BOARD_ASSOCIATE_READ', '준회원 게시판 읽기', CURRENT_TIMESTAMP()); -- 2
INSERT INTO AUTHORITY(AUTHORITY_NAME, AUTHORITY_DESC, CREATE_DT)
VALUES('BOARD_ASSOCIATE_WRITE', '준회원 게시판 쓰기', CURRENT_TIMESTAMP()); -- 3
INSERT INTO AUTHORITY(AUTHORITY_NAME, AUTHORITY_DESC, CREATE_DT)
VALUES('BOARD_REGULAR_READ', '정회원 게시판 읽기', CURRENT_TIMESTAMP()); -- 4
INSERT INTO AUTHORITY(AUTHORITY_NAME, AUTHORITY_DESC, CREATE_DT)
VALUES('BOARD_REGULAR_WRITE', '정회원 게시판 쓰기', CURRENT_TIMESTAMP()); -- 5
INSERT INTO AUTHORITY(AUTHORITY_NAME, AUTHORITY_DESC, CREATE_DT)
VALUES('BOARD_ADMIN_READ', '관리자 게시판 읽기', CURRENT_TIMESTAMP()); -- 6
INSERT INTO AUTHORITY(AUTHORITY_NAME, AUTHORITY_DESC, CREATE_DT)
VALUES('BOARD_ADMIN_WRITE', '관리자 게시판 쓰기', CURRENT_TIMESTAMP()); -- 7
INSERT INTO AUTHORITY(AUTHORITY_NAME, AUTHORITY_DESC, CREATE_DT)
VALUES('BOARD_NOTICE_READ', '공지 게시판 읽기', CURRENT_TIMESTAMP()); -- 8
INSERT INTO AUTHORITY(AUTHORITY_NAME, AUTHORITY_DESC, CREATE_DT)
VALUES('BOARD_NOTICE_WRITE', '공지 게시판 쓰기', CURRENT_TIMESTAMP()); -- 9

INSERT INTO URL_RESOURCES(RESOURCE_NAME, RESOURCE_PATTERN, REQUEST_MATCHER_TYPE, ORDERNUM, CREATE_DT) -- 1
VALUES('준회원 게시판 목록', '/board/associate/list.html', 'ANT', 1, CURRENT_TIMESTAMP());
INSERT INTO URL_RESOURCES(RESOURCE_NAME, RESOURCE_PATTERN, REQUEST_MATCHER_TYPE, ORDERNUM, CREATE_DT) -- 2
VALUES('준회원 게시판 상세화면', '/board/associate/view.html', 'ANT', 1, CURRENT_TIMESTAMP());
INSERT INTO URL_RESOURCES(RESOURCE_NAME, RESOURCE_PATTERN, REQUEST_MATCHER_TYPE, ORDERNUM, CREATE_DT) -- 3
VALUES('준회원 게시판 등록', '/board/associate/write.html', 'ANT', 1, CURRENT_TIMESTAMP());
INSERT INTO URL_RESOURCES(RESOURCE_NAME, RESOURCE_PATTERN, REQUEST_MATCHER_TYPE, ORDERNUM, CREATE_DT) -- 4
VALUES('준회원 게시판 수정', '/board/associate/update.html', 'ANT', 1, CURRENT_TIMESTAMP());
INSERT INTO URL_RESOURCES(RESOURCE_NAME, RESOURCE_PATTERN, REQUEST_MATCHER_TYPE, ORDERNUM, CREATE_DT) -- 5
VALUES('준회원 게시판 삭제', '/board/associate/delete.html', 'ANT', 1, CURRENT_TIMESTAMP());

INSERT INTO URL_RESOURCES(RESOURCE_NAME, RESOURCE_PATTERN, REQUEST_MATCHER_TYPE, ORDERNUM, CREATE_DT) -- 6
VALUES('정회원 게시판 목록', '/board/regular/list.html', 'ANT', 1, CURRENT_TIMESTAMP());
INSERT INTO URL_RESOURCES(RESOURCE_NAME, RESOURCE_PATTERN, REQUEST_MATCHER_TYPE, ORDERNUM, CREATE_DT) -- 7
VALUES('전회원 게시판 상세화면', '/board/regular/view.html', 'ANT', 1, CURRENT_TIMESTAMP());
INSERT INTO URL_RESOURCES(RESOURCE_NAME, RESOURCE_PATTERN, REQUEST_MATCHER_TYPE, ORDERNUM, CREATE_DT) -- 8
VALUES('정회원 게시판 등록', '/board/regular/write.html', 'ANT', 1, CURRENT_TIMESTAMP());
INSERT INTO URL_RESOURCES(RESOURCE_NAME, RESOURCE_PATTERN, REQUEST_MATCHER_TYPE, ORDERNUM, CREATE_DT) -- 9
VALUES('정회원 게시판 수정', '/board/regular/update.html', 'ANT', 1, CURRENT_TIMESTAMP());
INSERT INTO URL_RESOURCES(RESOURCE_NAME, RESOURCE_PATTERN, REQUEST_MATCHER_TYPE, ORDERNUM, CREATE_DT) -- 10
VALUES('정회원 게시판 삭제', '/board/regular/delete.html', 'ANT', 1, CURRENT_TIMESTAMP());

INSERT INTO URL_RESOURCES(RESOURCE_NAME, RESOURCE_PATTERN, REQUEST_MATCHER_TYPE, ORDERNUM, CREATE_DT) -- 11
VALUES('관리자 게시판 목록', '/board/admin/list.html', 'ANT', 1, CURRENT_TIMESTAMP());
INSERT INTO URL_RESOURCES(RESOURCE_NAME, RESOURCE_PATTERN, REQUEST_MATCHER_TYPE, ORDERNUM, CREATE_DT) -- 12
VALUES('관리자 게시판 상세화면', '/board/admin/view.html', 'ANT', 1, CURRENT_TIMESTAMP());
INSERT INTO URL_RESOURCES(RESOURCE_NAME, RESOURCE_PATTERN, REQUEST_MATCHER_TYPE, ORDERNUM, CREATE_DT) -- 13
VALUES('관리자 게시판 등록', '/board/admin/write.html', 'ANT', 1, CURRENT_TIMESTAMP());
INSERT INTO URL_RESOURCES(RESOURCE_NAME, RESOURCE_PATTERN, REQUEST_MATCHER_TYPE, ORDERNUM, CREATE_DT) -- 14
VALUES('관리자 게시판 수정', '/board/admin/update.html', 'ANT', 1, CURRENT_TIMESTAMP());
INSERT INTO URL_RESOURCES(RESOURCE_NAME, RESOURCE_PATTERN, REQUEST_MATCHER_TYPE, ORDERNUM, CREATE_DT) -- 15
VALUES('관리자 게시판 삭제', '/board/admin/delete.html', 'ANT', 1, CURRENT_TIMESTAMP());


INSERT INTO URL_RESOURCES(RESOURCE_NAME, RESOURCE_PATTERN, REQUEST_MATCHER_TYPE, ORDERNUM, CREATE_DT) -- 16
VALUES('공지사항 게시판 목록', '/board/notice/list.html', 'ANT', 1, CURRENT_TIMESTAMP());
INSERT INTO URL_RESOURCES(RESOURCE_NAME, RESOURCE_PATTERN, REQUEST_MATCHER_TYPE, ORDERNUM, CREATE_DT) -- 17
VALUES('공지사항 게시판 상세화면', '/board/notice/view.html', 'ANT', 1, CURRENT_TIMESTAMP());
INSERT INTO URL_RESOURCES(RESOURCE_NAME, RESOURCE_PATTERN, REQUEST_MATCHER_TYPE, ORDERNUM, CREATE_DT) -- 18
VALUES('공지사항 게시판 등록', '/board/notice/write.html', 'ANT', 1, CURRENT_TIMESTAMP());
INSERT INTO URL_RESOURCES(RESOURCE_NAME, RESOURCE_PATTERN, REQUEST_MATCHER_TYPE, ORDERNUM, CREATE_DT) -- 19
VALUES('공지사항 게시판 수정', '/board/notice/update.html', 'ANT', 1, CURRENT_TIMESTAMP());
INSERT INTO URL_RESOURCES(RESOURCE_NAME, RESOURCE_PATTERN, REQUEST_MATCHER_TYPE, ORDERNUM, CREATE_DT) -- 20
VALUES('공지사항 게시판 삭제', '/board/notice/delete.html', 'ANT', 1, CURRENT_TIMESTAMP());

INSERT INTO URL_RESOURCES_AUTHORITY(URL_RESOURCES_IDX, AUTHORITY_IDX)
VALUES(1, 2); -- 준회원 게시판 목록 / 준회원 게시판 읽기
INSERT INTO URL_RESOURCES_AUTHORITY(URL_RESOURCES_IDX, AUTHORITY_IDX)
VALUES(1, 3); -- 준회원 게시판 목록 / 준회원 게시판 쓰기
INSERT INTO URL_RESOURCES_AUTHORITY(URL_RESOURCES_IDX, AUTHORITY_IDX)
VALUES(2, 2); -- 준회원 게시판 상세화면 / 준회원 게시판 읽기
INSERT INTO URL_RESOURCES_AUTHORITY(URL_RESOURCES_IDX, AUTHORITY_IDX)
VALUES(2, 3); -- 준회원 게시판 상세화면 / 준회원 게시판 쓰기
INSERT INTO URL_RESOURCES_AUTHORITY(URL_RESOURCES_IDX, AUTHORITY_IDX)
VALUES(3, 3); -- 준회원 게시판 등록 / 준회원 게시판 쓰기
INSERT INTO URL_RESOURCES_AUTHORITY(URL_RESOURCES_IDX, AUTHORITY_IDX)
VALUES(4, 3); -- 준회원 게시판 수정 / 준회원 게시판 쓰기
INSERT INTO URL_RESOURCES_AUTHORITY(URL_RESOURCES_IDX, AUTHORITY_IDX)
VALUES(5, 3); -- 준회원 게시판 삭제 / 준회원 게시판 쓰기

INSERT INTO URL_RESOURCES_AUTHORITY(URL_RESOURCES_IDX, AUTHORITY_IDX)
VALUES(6, 4); -- 정회원 게시판 목록 / 정회원 게시판 읽기
INSERT INTO URL_RESOURCES_AUTHORITY(URL_RESOURCES_IDX, AUTHORITY_IDX)
VALUES(6, 5); -- 정회원 게시판 목록 / 정회원 게시판 쓰기
INSERT INTO URL_RESOURCES_AUTHORITY(URL_RESOURCES_IDX, AUTHORITY_IDX)
VALUES(7, 4); -- 정회원 게시판 상세화면 / 정회원 게시판 읽기
INSERT INTO URL_RESOURCES_AUTHORITY(URL_RESOURCES_IDX, AUTHORITY_IDX)
VALUES(7, 5); -- 정회원 게시판 상세화면 / 정회원 게시판 쓰기
INSERT INTO URL_RESOURCES_AUTHORITY(URL_RESOURCES_IDX, AUTHORITY_IDX)
VALUES(8, 5); -- 정회원 게시판 등록 / 정회원 게시판 쓰기
INSERT INTO URL_RESOURCES_AUTHORITY(URL_RESOURCES_IDX, AUTHORITY_IDX)
VALUES(9, 5); -- 정회원 게시판 수정 / 정회원 게시판 쓰기
INSERT INTO URL_RESOURCES_AUTHORITY(URL_RESOURCES_IDX, AUTHORITY_IDX)
VALUES(10, 5); -- 정회원 게시판 삭제 / 정회원 게시판 쓰기

